package dev.jayms.render;
import java.util.*;
import org.junit.jupiter.api.Test;
import static dev.jayms.render.GraphicsProfile.*;
import static org.junit.jupiter.api.Assertions.*;
class GraphicsTransactionTest {
 static class Resource implements AutoCloseable {boolean closed;public void close(){assertFalse(closed);closed=true;}}
 static class Display implements GraphicsTransaction.Display {String mode="WINDOWED";public Object capture(){return mode;}public void apply(GraphicsProfile p){mode=p.get(Key.DISPLAY_MODE);}public void restore(Object s,GraphicsProfile p){mode=(String)s;}}
 static class Store implements GraphicsTransaction.Store {GraphicsProfile saved;boolean marker,fail;public void save(GraphicsProfile p){if(fail)throw new IllegalStateException();saved=p;}public void beginRisk(GraphicsProfile p){saved=p;marker=true;}public void endRisk(){marker=false;}}
 @Test void qualitySavesButFailureRetainsOldRenderer(){var old=new Resource();var store=new Store();var display=new Display();var cap=new Capabilities(4,4096,16,List.of());var current=preset(Preset.BALANCED);var published=new Resource[]{old};try(var t=new GraphicsTransaction<>(old,current,cap,display,p->new Resource(),store,r->published[0]=r)){store.fail=true;assertFalse(t.apply(preset(Preset.LOW),0));assertSame(old,published[0]);assertFalse(old.closed);assertEquals(current,t.requested());store.fail=false;assertTrue(t.apply(preset(Preset.LOW),0));assertTrue(old.closed);assertEquals(Preset.LOW,store.saved.preset());assertFalse(t.pending());}}
 @Test void riskyChangeNotSavedUntilConfirmedAndFocusLossReverts(){var old=new Resource();var store=new Store();var display=new Display();var cap=new Capabilities(4,4096,16,List.of());var current=preset(Preset.BALANCED);var published=new Resource[]{old};try(var t=new GraphicsTransaction<>(old,current,cap,display,p->new Resource(),store,r->published[0]=r)){var draft=current.with(Key.DISPLAY_MODE,"BORDERLESS");assertTrue(t.apply(draft,100));assertEquals(current,store.saved);assertTrue(store.marker);assertEquals(15,t.remaining(100));Resource candidate=published[0];t.tick(101,false);assertSame(old,published[0]);assertTrue(candidate.closed);assertFalse(old.closed);assertEquals("WINDOWED",display.mode);assertFalse(store.marker);assertTrue(t.apply(draft,200));t.confirm();assertEquals(draft,store.saved);assertTrue(old.closed);assertFalse(t.pending());}}
 @Test void timeoutAndPrepareFailureRevert(){var old=new Resource();var store=new Store();var display=new Display();var cap=new Capabilities(4,4096,1,List.of());var profile=preset(Preset.BALANCED);try(var t=new GraphicsTransaction<>(old,profile,cap,display,p->{throw new IllegalStateException("allocation failure");},store,r->{})){assertFalse(t.apply(profile.with(Key.DISPLAY_MODE,"BORDERLESS"),0));assertFalse(old.closed);assertEquals("WINDOWED",display.mode);assertFalse(store.marker);}try(var t=new GraphicsTransaction<>(old,profile,cap,display,p->new Resource(),store,r->{})){assertTrue(t.apply(profile.with(Key.DISPLAY_MODE,"BORDERLESS"),0));t.tick(15_000_000_000L,true);assertFalse(t.pending());assertFalse(old.closed);}}
}
