import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,models} from './game.mjs';
test('models contain voxel cells and three distinct aliens',()=>{assert.equal(new Set([models.squid.join(),models.crab.join(),models.octopus.join()]).size,3);for(const rows of Object.values(models))assert(rows.every(r=>r.length===rows[0].length&&/^[01]+$/.test(r)));});
test('movement clamps, fire cooldown, pause and restart',()=>{const g=new Game();g.restart();for(let i=0;i<100;i++)g.update(.05,{axis:-1,fire:true});assert.equal(g.player,20);assert(g.shots.length<20);g.pause();const x=g.player;g.update(.05,{axis:1});assert.equal(g.player,x);g.restart();assert.equal(g.lives,3);assert.equal(g.score,0);});
test('alien kill scores once; last kill advances and resets',()=>{const g=new Game();g.restart();g.aliens=[{x:240,y:200,points:30}];g.shots=[{x:240,y:205},{x:240,y:205}];g.update(.01);assert.equal(g.score,30);assert.equal(g.wave,2);assert.equal(g.aliens.length,45);assert.equal(g.shots.length,0);assert.equal(g.enemyShots.length,0);});
test('both sides erode shields',()=>{for(const enemy of [false,true]){const g=new Game();g.restart();g.shields=[{x:100,y:440},{x:105,y:440}];g[enemy?'enemyShots':'shots']=[{x:100,y:enemy?435:445}];g.update(.01);assert.equal(g.shields.length,0);assert.equal(g[enemy?'enemyShots':'shots'].length,0);}});
test('life loss, immunity, game over and invasion',()=>{const g=new Game();g.restart();g.enemyShots=[{x:240,y:515}];g.update(.01);assert.equal(g.lives,2);g.enemyShots=[{x:240,y:515}];g.update(.01);assert.equal(g.lives,2);g.invulnerable=0;g.lives=1;g.enemyShots=[{x:240,y:515}];g.update(.01);assert.equal(g.state,'over');g.restart();g.aliens[0].y=490;g.update(.01);assert.equal(g.state,'over');});
test('fleet reverses and descends; bottom shooters; saucer bonus',()=>{const g=new Game(()=>0);g.restart();g.aliens=[{x:460,y:100,points:10},{x:460,y:150,points:10}];g.enemyClock=0;g.update(.05);assert.equal(g.direction,-1);assert.equal(g.aliens[0].y,115);assert(g.enemyShots[0].y>165);g.saucer={x:240,y:38};g.shots=[{x:240,y:42}];g.update(.01);assert.equal(g.score,100);assert.equal(g.saucer,null);});
test('large background delta bounded and offscreen projectiles recycled',()=>{const g=new Game();g.restart();g.shots=[{x:10,y:1}];g.enemyShots=[{x:10,y:569}];g.update(100,{axis:1});assert(g.player<=252);assert.equal(g.shots.length,0);assert.equal(g.enemyShots.length,0);});

test('slow frame projectile sweeps across alien and shield',()=>{const g=new Game();g.restart();g.aliens=[{x:240,y:200,points:30}];g.shots=[{x:240,y:205}];g.update(.05);assert.equal(g.wave,2);assert.equal(g.score,30);g.shields=[{x:100,y:440}];g.shots=[{x:100,y:450}];g.update(.05);assert.equal(g.shields.length,0);});

test('levels alternate classic and cockpit; restart restores classic',()=>{const g=new Game();g.restart();for(let wave=1;wave<=4;wave++){assert.equal(g.wave,wave);assert.equal(g.perspective,wave%2?'classic':'cockpit');g.aliens=[];g.update(.01);}g.restart();assert.equal(g.wave,1);assert.equal(g.perspective,'classic');});
