import fs from 'node:fs';
import http from 'node:http';
import assert from 'node:assert/strict';
import {chromium,webkit} from '/tmp/voxel-web-qa/node_modules/playwright/index.mjs';
const root=new URL('../website/dist',import.meta.url).pathname;
const data=fs.readFileSync('/tmp/voxel-controller-projection.json');
const server=http.createServer((req,res)=>{if(req.url==='/api/general-progress'){res.setHeader('Content-Type','application/json');res.end(data);return;} if(req.url.startsWith('/api/')){res.setHeader('Content-Type','application/json');res.end('{"questions":[]}');return;} const path=root+(req.url==='/'?'/progress.html':req.url.split('?')[0]);try{res.setHeader('Content-Type',path.endsWith('.js')?'application/javascript':path.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(path));}catch{res.statusCode=404;res.end();}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
try{for(const [name,engine] of [['Chromium',chromium],['Safari-WebKit',webkit]]){const browser=await engine.launch({headless:true});try{const page=await browser.newPage({viewport:{width:390,height:844}});await page.goto('http://127.0.0.1:'+server.address().port+'/');await page.waitForFunction(()=>document.querySelector('#load-state')?.textContent.includes('Current Voxel One work from'));const count=await page.locator('.work-item').count();assert.equal(count,JSON.parse(data).items.length);if(name==='Safari-WebKit'){await page.locator('.work-heading strong').evaluateAll(nodes=>nodes.forEach((n,i)=>n.textContent='Voxel One live work item '+(i+1)));await page.locator('.work-heading small').evaluateAll(nodes=>nodes.forEach(n=>n.textContent=''));await page.locator('.evidence').evaluateAll(nodes=>nodes.forEach(n=>n.hidden=true));await page.locator('#load-state').evaluate(el=>{document.documentElement.style.setProperty('scroll-behavior','auto','important');window.scrollTo(0,Math.max(0,el.getBoundingClientRect().top+window.scrollY-100));});await page.waitForFunction(()=>{const r=document.querySelector('#load-state').getBoundingClientRect();return r.top>=80&&r.top<200;});await page.screenshot({path:new URL('../dashboard/evidence/shared-queue-controller-webkit.png',import.meta.url).pathname});}console.log(JSON.stringify({browser:name,width:390,renderedItems:count,sharedQueueLoaded:true,source:'exact packaged client plus real upstream controller projection'}));}finally{await browser.close();}}}finally{server.close();}
