import assert from 'node:assert/strict';
import test from 'node:test';
import {generalProgress} from '../progress_bridge.mjs';
const userRequest=()=>new Request('https://voxel-one.example/api/general-progress',{headers:{'oai-authenticated-user-id':'test-owner'}});
const env={GENERAL_DASHBOARD_AUTH:'fictional-platform-service-key',GENERAL_DASHBOARD_BRIDGE_KEY:'fictional-read-only-machine-key',ASSETS:{fetch:async()=>Response.json({release:{name:'Recorded playtest'},verification:{tests:166}})}};
test('bridge rejects anonymous and service callers without browser identity',async()=>{let called=false;const r=await generalProgress(new Request('https://voxel-one.example/api/general-progress',{headers:{'x-voxel-agent':'1'}}),env,async()=>{called=true;});assert.equal(r.status,401);assert.equal(called,false);});
test('unconfigured queue returns recoverable unavailable status',async()=>{const r=await generalProgress(userRequest(),{},()=>{throw Error('Must not fetch');});assert.equal(r.status,503);});
test('fixed Voxel projection forwards credentials only to General Site and excludes private fields',async()=>{
 let target,headers;const r=await generalProgress(userRequest(),env,async(url,options)=>{target=url;headers=options.headers;return Response.json({schemaVersion:1,items:[{id:'work-1',title:'Example',status:'waiting_review',prompt:'Private prompt must be excluded',leaseToken:'Private lease must be excluded',checkpoint:'Private agent state',evidence:[{label:'Screenshot',url:'https://evidence.example/a.png'},{label:'unsafe',url:'javascript:alert(1)'}]}]});});
 assert.equal(target,'https://codex-development-dashboard.jamesleaver1.chatgpt.site/api/applications/voxel-one/progress?agentId=voxel-bridge');assert.equal(headers['X-Codex-Agent-Key'],env.GENERAL_DASHBOARD_BRIDGE_KEY);const data=await r.json();assert.equal(data.items.length,1);assert.equal(data.items[0].status,'waiting_review');assert.equal(data.items[0].evidence.length,1);assert.equal(data.items[0].evidence[0].kind,'image');assert.equal(data.verification.tests,166);const text=JSON.stringify(data);for(const hidden of ['Private prompt','Private lease','Private agent state',env.GENERAL_DASHBOARD_AUTH,env.GENERAL_DASHBOARD_BRIDGE_KEY])assert.equal(text.includes(hidden),false);
});
test('upstream errors and invalid schema do not leak private diagnostics',async()=>{for(const response of [()=>Response.json({error:'Private upstream diagnostic'}, {status:403}),()=>Response.json({schemaVersion:2,items:[]})]){const r=await generalProgress(userRequest(),env,response);assert.equal(r.status,503);assert.equal((await r.text()).includes('Private upstream'),false);}});
